from __future__ import annotations

import shutil
from pathlib import Path

from forge_switcheroo.constants import GITHUB, GITLAB
from forge_switcheroo.models import Forge


def _detected_commands(project: Path) -> tuple[list[str], list[str]]:
    if (project / "pyproject.toml").exists():
        return ["python -m pip install ."], ["python -m pytest"]
    if (project / "package.json").exists():
        return ["npm ci"], ["npm test"]
    if (project / "Cargo.toml").exists():
        return [], ["cargo test --all-targets"]
    if (project / "go.mod").exists():
        return [], ["go test ./..."]
    return [], ["echo 'TODO: configure project checks'"]


def generate_ci(project: Path, target: Forge) -> tuple[str, str | None]:
    install, checks = _detected_commands(project)
    if target is Forge.GITLAB:
        output = project / ".gitlab-ci.yml"
        if output.exists():
            return "Existing GitLab pipeline preserved", None
        commands = "\n".join(f"    - {command}" for command in [*install, *checks])
        output.write_text(
            "# Generated by forge-switcheroo; review before use.\n"
            "stages:\n  - test\n\n"
            "test:\n  stage: test\n  script:\n"
            f"{commands}\n",
            encoding="utf-8",
        )
        return "Generated .gitlab-ci.yml pipeline", "The generated pipeline requires manual review."

    output = project / GITHUB / "workflows" / "ci.yml"
    if output.exists():
        return "Existing GitHub workflow preserved", None
    output.parent.mkdir(parents=True, exist_ok=True)
    commands = "\n".join(f"      - run: {command}" for command in [*install, *checks])
    output.write_text(
        "# Generated by forge-switcheroo; review before use.\n"
        "name: CI\non: [push, pull_request]\n\n"
        "jobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        f"{commands}\n",
        encoding="utf-8",
    )
    return (
        "Generated .github/workflows/ci.yml workflow",
        "The generated workflow requires manual review.",
    )


def convert_templates(project: Path, source: Forge, target: Forge) -> list[str]:
    if source is Forge.GITHUB and target is Forge.GITLAB:
        source_dir = project / GITHUB / "ISSUE_TEMPLATE"
        target_dir = project / GITLAB / "issue_templates"
    else:
        source_dir = project / GITLAB / "issue_templates"
        target_dir = project / GITHUB / "ISSUE_TEMPLATE"

    if not source_dir.is_dir():
        return ["No source issue templates found"]
    target_dir.mkdir(parents=True, exist_ok=True)
    copied = 0
    for template in source_dir.glob("*.md"):
        destination = target_dir / template.name
        if not destination.exists():
            shutil.copy2(template, destination)
            copied += 1
    return [f"Copied {copied} issue template(s) to {target_dir.relative_to(project)}"]
